language: node_js
node_js:
  - "node"
  - "8"
before_install:
- openssl aes-256-cbc -K $encrypted_3c41409f0d74_key -iv $encrypted_3c41409f0d74_iv
  -in hello-world-react-pipe-e73d4d1b1132.json.enc -out hello-world-react-pipe-e73d4d1b1132.json
  -d
install:
- npm install
script:
- echo "no script"
deploy:
  provider: gae
  keyfile: hello-world-react-pipe-e73d4d1b1132.json
  project: hello-world-react-pipe
  on: master
