language: node_js
before_install:
- openssl aes-256-cbc -K $encrypted_3c41409f0d74_key -iv $encrypted_3c41409f0d74_iv -in hello-world-react-pipe-e73d4d1b1132.json.enc -out ~\/workspaces/react/hello-world-react-pipe-e73d4d1b1132.json -d
install:
- npm start
script:
- echo "no script"
deploy:
  provider: gae
  keyfile: hello-world-react-pipe-e73d4d1b1132.json.enc
  project: hello-world-react-pipe
  on: master